# Basic
title: 白木幺
subtitle: 业精于勤荒于嬉 行成于思毁于随
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">下载这个博客主题</a>
description: 为所欲为所欲为
creator: <a href="https://leliu.github.io">@LiuLe</a>

url: "https://github.com/leliu/leliu.github.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/leliu'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    #weibo: onevcat
    github: leliu
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: lele.liu@hotmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
